### ISSUE TITLE
Make `/registerUrl` requests idempotent

### ISSUE THREAD

**Issue by smcclure17** [covid-projections/act-now-links-service#7]
There's a possible race condition where two share links can be created for the same URL if two requests are made near simultaneously. We expect there to only ever be one share link per URL. 

Can maybe do this by seeding the "random" hash/share link ID with the url? This will prevent multiple share links from being created, but still has issues. If two requests are sent simultaneously to create a share link for the same URL but otherwise different params, I'm not sure which data will be saved? Will a collision cause undefined behavior?

**Comment by pnavarrc** [comment]
> We expect there to only ever be one share link per URL.

I'm not sure if we wan that for a few reasons:

- There are some use cases where users might want to generate different versions of the social meta tags (A/B testing, wanting to generate new social previews at different points in time, etc)
- If the target URL is expected to be unique, users will need to be able to edit the meta tags, which will require us to implement some authentication/account system to ensure that whoever is changing the meta tags is authorized to do so

Maybe we don't need to allow users to fetch share links by target URL? 

---

Another option is to make `/registerUrl` requests always return the same link given the same data parameters. For example, we could calculate a hash using both the URL and the parameters?

```ts
hash(`${url}_${JSON.stringify(data)}`)
```

that way we could generate unique, predictable link IDs while allowing multiple share links per URL.

**Comment by smcclure17** [comment]
Yeah good points--the one-link-per-url was largely for the convenience of being able to easily look up/map share links, but I agree it's definitely beneficial /better to allow multiple links per URL for the reasons you mention.

I think it's useful to be able to lookup the share links (either by the URL or all of the params) so that e.g. on the frontend we never have to keep track of what links exist, or what they are.

So, I like the idea of calculating the hash from the full set of params, as that seems to give us the best of both worlds (allows multiple links per URL, but still allows us to easily fetch/lookup links)
